import dash
from dash import html, dcc
import dash_bootstrap_components as dbc
from config.config import CONFIG

dash.register_page(__name__, path="/", name="About")

layout = dbc.Container(
    [
        html.Div(
            [
                html.H2(
                    html.B("College Football Fourth Down Decision Analytics"),
                    className="mt-4",
                    style={"color": "#000"},
                ),
            ],
            style={"overflow": "hidden"},
        ),
        # "An analytical look at fourth down decisions in college football:" in italics
        html.P(
            [
                html.Em(
                    "Data-driven evaluation of fourth down decisions using win probability modeling"
                )
            ],
            className="mb-4",
        ),
        html.Img(
            src="/assets/images/4th_down.jpg",
            style={"width": "100%", "height": "auto"},
            className="mb-4",
        ),
        html.P(
            [
                "This website is a tool for exploring college football team and coach tendencies on fourth down decision making. All fourth down recommendations are generated by a machine learning decision engine that evaluates the expected win probability of each available option."
            ]
        ),
        html.P(
            [
                "For every fourth down play, the engine compares the expected win probability of going for it, punting, and attempting a field goal. The recommended decision is the one that maximizes expected win probability, accounting for both the value and likelihood of each possible outcome. Model inputs include game state, weather, stadium elevation, pregame point spread, and pregame team Elo ratings."
            ]
        ),
        html.Img(
            src="/assets/images/architecture.png",
            style={
                "width": "100%",
                "max-width": "900px",
                "height": "auto",
                "display": "block",
                "margin": "0 auto",
                "box-sizing": "border-box",
                "padding-left": CONFIG["padding-left"],
                "padding-right": CONFIG["padding-right"],
            },
            className="my-4",
        ),
        html.H3(html.B("Site Overview"), className="mt-4", style={"color": "#000"}),
        html.P(
            [
                "The site is organized into several main sections, accessible via the navigation bar at the top of the page:"
            ]
        ),
        html.Ol(
            [
                html.Li(
                    [
                        dcc.Link(
                            [
                                html.B("Teams"),
                                html.I(
                                    className="bi bi-link-45deg ms-1",
                                    style={"font-size": "0.9em"},
                                ),
                            ],
                            href="/team-tendencies",
                            style={"text-decoration": "none", "color": "inherit"},
                        ),
                        html.Br(),
                        "Explore team-level fourth down tendencies for a selected season or range of seasons. "
                        "This includes how often teams follow model recommendations and the cumulative win probability impact of their decisions.",
                    ]
                ),
                html.Br(),
                html.Li(
                    [
                        dcc.Link(
                            [
                                html.B("Coaches"),
                                html.I(
                                    className="bi bi-link-45deg ms-1",
                                    style={"font-size": "0.9em"},
                                ),
                            ],
                            href="/coach-tendencies",
                            style={"text-decoration": "none", "color": "inherit"},
                        ),
                        html.Br(),
                        "Analyze coaching tendencies on fourth down, including how individual coaches compare to peers "
                        "and how their decision-making behavior evolves over time.",
                    ]
                ),
                html.Br(),
                html.Li(
                    [
                        dcc.Link(
                            [
                                html.B("Plays"),
                                html.I(
                                    className="bi bi-link-45deg ms-1",
                                    style={"font-size": "0.9em"},
                                ),
                            ],
                            href="/game-decisions",
                            style={"text-decoration": "none", "color": "inherit"},
                        ),
                        html.Br(),
                        "Inspect play-level detail for every fourth down decision. Filter by team, season, and optionally week, and view:",
                        html.Ul(
                            [
                                html.Li(
                                    "Team and opponent Elo ratings at the time of the play"
                                ),
                                html.Li(
                                    "Game state including score, quarter, time remaining, down, distance, and yards to goal"
                                ),
                                html.Li("Expected win probability for each decision"),
                                html.Li(
                                    "Model recommendation, actual decision made, and play description"
                                ),
                            ]
                        ),
                        "This view can be used to identify the best and worst decisions by a team, or to sanity check whether a decision aligned with the model recommendation.",
                    ]
                ),
                html.Br(),
                html.Li(
                    [
                        dcc.Link(
                            [
                                html.B("Analysis"),
                                html.I(
                                    className="bi bi-link-45deg ms-1",
                                    style={"font-size": "0.9em"},
                                ),
                            ],
                            href="/analysis",
                            style={"text-decoration": "none", "color": "inherit"},
                        ),
                        html.Br(),
                        "Read longer-form writeups on the models powering the decision engine, including:",
                        html.Ul(
                            [
                                html.Li("Win probability model"),
                                html.Li("Fourth down conversion probability model"),
                                html.Li("Field goal make probability model"),
                                html.Li("Punt yards to goal model"),
                            ]
                        ),
                        "The section also includes analysis of team-level decision making in the 2025 season "
                        "and coaching tendencies toward aggressive or conservative behavior.",
                    ]
                ),
            ]
        ),
        html.H3(html.B("Key Metrics"), className="mt-4", style={"color": "#000"}),
        html.P(
            [
                "Across the ",
                dcc.Link(
                    html.B("Teams"),
                    href="/team-tendencies",
                    style={"color": "inherit", "text-decoration": "none"},
                ),
                " and ",
                dcc.Link(
                    html.B("Coaches"),
                    href="/coach-tendencies",
                    style={"color": "inherit", "text-decoration": "none"},
                ),
                " tabs, several summary metrics are visualized:",
            ]
        ),
        html.Ul(
            [
                html.Li(
                    [
                        html.B("Go-For-It Rate When Recommended"),
                        html.Br(),
                        "The percentage of fourth down plays where a team or coach goes for it when the model recommends doing so. A recommendation to go for it occurs when going for it has higher expected win probability than both punting and attempting a field goal. For example, on a 4th & 1 at the opponent’s 30-yard line while down 7 with 4:00 remaining, the model may estimate a 23 percent win probability if the team goes for it, compared to 15 percent for a field goal attempt and 10 percent for a punt. In this case, going for it is the recommended decision.",
                    ]
                ),
                html.Img(
                    src="/assets/images/example_4th_down.png",
                    style={
                        "width": "100%",
                        "max-width": "600px",
                        "height": "auto",
                        "display": "block",
                        "margin": "0 auto",
                        "box-sizing": "border-box",
                        "padding-left": CONFIG["padding-left"],
                        "padding-right": CONFIG["padding-right"],
                    },
                    className="my-4",
                ),
                html.Br(),
                html.Li(
                    [
                        html.B("Win Probability Lost Per Season"),
                        html.Br(),
                        "The total expected win probability lost over a season when a team or coach chooses to punt or kick a field goal despite going for it having higher expected win probability. For example, if going for it yields 53 percent expected win probability and a field goal yields 50 percent, the decision of kicking a field goal results in a 3 percent win probability loss.",
                    ]
                ),
                html.Br(),
                html.Li(
                    [
                        html.B("Go-For-It Rate Over Time"),
                        html.Br(),
                        "A longitudinal view of how fourth down aggressiveness has changed from 2013 to the present, highlighting trends toward more aggressive or conservative decision making.",
                    ]
                ),
            ]
        ),
        html.H3(html.B("Data and Feedback"), className="mt-4", style={"color": "#000"}),
        html.P(
            [
                "All data used in this project is sourced from the ",
                html.A(
                    "CollegeFootballData",
                    href="https://collegefootballdata.com/",
                    target="_blank",
                    style={"text-decoration": "none"},
                ),
                " API. Many thanks to the contributors and maintainers of that resource.",
            ]
        ),
        html.P(
            [
                "Feedback is always welcome. You can reach me at ",
                html.Span("lneuendorf@proton.me", style={"text-decoration": "underline"}),
                ", or via the linked social media accounts in the site footer.",
            ],
            className="mb-4",
        ),
    ],
    fluid=True,
    style={
        "max-width": "1000px",
        "padding-left": CONFIG["padding-left"],
        "padding-right": CONFIG["padding-right"],
        "padding-bottom": "1rem",
    },
    className="responsive-container",
)
